GET http://localhost:3001/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRpMTIiLCJpYXQiOjE2ODYyMDY1NjMsImV4cCI6MTY4NjIxMDE2M30.QpQr3NWqRrQ_ljV-FP2rOtWa9BK53SzoDu4EpkLvzcw
###

GET http://localhost:3001/getProfile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODU4NTg0NDksImV4cCI6MTY4NTg1ODQ3OX0.eHl9PC2A-OAWshFz2H_IQq0FN1Ad1ikK1D57Qc2jgTs
Content-Type: application/json

{
    "username": "rizal36"
}

###
POST http://localhost:3001/insertProfile
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRpMTIiLCJpYXQiOjE2ODU5MzUxNDksImV4cCI6MTY4NTkzODc0OX0.b6m9AYDXM8wnD0N5ENj8jJclyCndUsO0OQKyUdRKW7g
Content-Type: application/json

{   "username": "adi12",
    "first_name": "Ahmad Adi",
    "last_name": "Iskandar Ubaidah",
    "phone": "1111111",
    "gender": "L",
    "address": "Tompokersan, Lumajang, Jawa Timur"
}

###
POST http://localhost:3001/changePassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRpMTIiLCJpYXQiOjE2ODYyMDYzNjgsImV4cCI6MTY4NjIwOTk2OH0.WEL1dsTbSSPxE1Uz5kpizh8cZrDbYp0brxMQ_gwf4dY
Content-Type: application/json

{
    "username": "adi12",
    "old_password": "123",
    "new_password": "1234"
}


###
POST http://localhost:3002/token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkaTEyIiwicGFzc3dvcmQiOiIxMjMiLCJpYXQiOjE2ODU5NzQ2MzZ9.E6RnFXvvWNOq7hsnKf6Gsp2RMHm4nv8JzcKd3tg2niI


###
POST http://localhost:3002/register
Content-Type: application/json

{
    "username": "rizal36",
    "password": "12343"
}

###

POST http://localhost:3002/login
Content-Type: application/json

{
    "username": "adi12",
    "password": "1234"
}

###

POST http://localhost:3002/logout
Content-Type: application/json

{
    "username": "adi12"
}
